// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2jKIBswx4-hlDySTz7wPyCdOqGljxcuE',
    appId: '1:776427672014:web:04adc4039fe0ddee909b9f',
    messagingSenderId: '776427672014',
    projectId: 'myfirstapp-690f6',
    authDomain: 'myfirstapp-690f6.firebaseapp.com',
    storageBucket: 'myfirstapp-690f6.appspot.com',
    measurementId: 'G-6SEL11HMJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfrD0puwGsxnq1_KJrnRuC1z2rKAAa9xE',
    appId: '1:776427672014:android:d548a05dd06cf7f3909b9f',
    messagingSenderId: '776427672014',
    projectId: 'myfirstapp-690f6',
    storageBucket: 'myfirstapp-690f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSBNA76W61as5-3T9-O_AI3_IvqFeh2ps',
    appId: '1:776427672014:ios:610298de73ed4a50909b9f',
    messagingSenderId: '776427672014',
    projectId: 'myfirstapp-690f6',
    storageBucket: 'myfirstapp-690f6.appspot.com',
    iosClientId: '776427672014-t7nrequp71l2ho93n74oq0f066gugtmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseproject',
  );
}
